
package jdbc.empleados.ws.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmpleadosServiceImplService", targetNamespace = "http://server.ws.empleados.jdbc/", wsdlLocation = "http://localhost:8888/ws/empleados?wsdl")
public class EmpleadosServiceImplService
    extends Service
{

    private final static URL EMPLEADOSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLEADOSSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName EMPLEADOSSERVICEIMPLSERVICE_QNAME = new QName("http://server.ws.empleados.jdbc/", "EmpleadosServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/ws/empleados?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLEADOSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        EMPLEADOSSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public EmpleadosServiceImplService() {
        super(__getWsdlLocation(), EMPLEADOSSERVICEIMPLSERVICE_QNAME);
    }

    public EmpleadosServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLEADOSSERVICEIMPLSERVICE_QNAME, features);
    }

    public EmpleadosServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, EMPLEADOSSERVICEIMPLSERVICE_QNAME);
    }

    public EmpleadosServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLEADOSSERVICEIMPLSERVICE_QNAME, features);
    }

    public EmpleadosServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmpleadosServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmpleadosService
     */
    @WebEndpoint(name = "EmpleadosServiceImplPort")
    public EmpleadosService getEmpleadosServiceImplPort() {
        return super.getPort(new QName("http://server.ws.empleados.jdbc/", "EmpleadosServiceImplPort"), EmpleadosService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmpleadosService
     */
    @WebEndpoint(name = "EmpleadosServiceImplPort")
    public EmpleadosService getEmpleadosServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.ws.empleados.jdbc/", "EmpleadosServiceImplPort"), EmpleadosService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLEADOSSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw EMPLEADOSSERVICEIMPLSERVICE_EXCEPTION;
        }
        return EMPLEADOSSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
